### ISSUE TITLE
[Todo]: something feature todo

### ISSUE THREAD

**Issue by ChelesteWang** [xieyezi/semi-design-pro#11]
## English
- [ ] Initialize the project template scaffolding
- [ ] Perfect the 'icon' component
- [ ] Completes the base form 'form' page
- [ ] Completes the step form 'form' page
- [ ] Completes the base list 'table' page
- [ ] Complete query list 'table' page

## 中文
- [ ] 初始化项目模板脚手架
- [ ] 完善 `icon` 组件
- [ ] 补全基础表单 `form` 页面
- [ ] 补全分步表单 `form` 页面
- [ ] 补全基础列表 `table` 页面
- [ ] 补全查询列表 `table` 页面

**Comment by MrPand111** [comment]
https://github.com/xieyezi/semi-design-pro/pull/12 脚手架

**Comment by AndroidMilk** [comment]
icon组件我给你提个pr

**Comment by ChelesteWang** [comment]
> icon组件我给你提个pr

Thanks a lot
