### ISSUE TITLE
[Done]: Something to do

### ISSUE THREAD

**Issue by ChelesteWang** [xieyezi/semi-design-pro#6]
## English
- [x] add result and abnormal pages #5 
- [x] fix menu scroll bar #9 
- [x] fix typo of `pravateRoute` #8 

## 中文
- [x] 添加结果页与异常页 #5 
- [x] 修复菜单栏滚动条 #9 
- [x] 修复文件`pravateRoute`命名错误 #8

**Comment by xieyezi** [comment]
@ChelesteWang already merged, thanks!
